name: amin_diagonastic
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  cached_network_image: ^3.2.0
  table_calendar: ^3.0.0
  flutter_spinkit: ^5.1.0
  persistent_bottom_nav_bar: ^4.0.2
  circular_profile_avatar: ^2.0.5
  flutter_svg: ^1.0.3
  flutter_custom_clippers: ^2.0.0
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.13
  flutter_switch: ^0.3.2

  badges: ^2.0.2
  date_picker_timeline: ^1.2.3
  shimmer: ^2.0.0
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  image_picker: ^0.8.4+5
  show_up_animation: ^2.0.0
  page_transition: ^2.0.5
  textfield_tags: ^2.0.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sanchez
      fonts:
        - asset: assets/fonts/Sanchez-Regular.ttf
